<!DOCTYPE html>
<html>
    <head>
        <title>Crumble&Flake</title>

        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="CSS3/estilosbarra.css">
        <link rel="stylesheet" type="text/css" href="CSS3/estiloscabezera.css">

        <!-- BACGRO UND Y LINKS -->

        <link rel="icon" type="Imagenes/png" href="Imagenes/Logo_Empresa.png">
        <script src="https://kit.fontawesome.com/d596bebcab.js" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Urbanist&display=swap" rel="stylesheet">


        <!-- RESEÑAS -->
        <link rel="stylesheet" type="text/css" href="CSS3/reseñas.css">
        <script type="text/javascript" src="JS/reseña.js"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- FOOTER -->
        <link rel="stylesheet" type="text/css" href="CSS3/footer.css">

    </head>

    <body>

    <?php
    include 'encabezado.php';
    ?>

        <div class="portada">
            <span class="imgportada" ><img src="Imagenes/portada.jpg" alt=" "></span>
        </div>


        <div class="social">
            <ul>

                <li><a href="http://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook-f"></i></a></li>

                <li><a href="http://www.twitter.com/" target="_blank"><i class="fa-brands fa-twitter"></i></a></li>

                <li><a href="http://www.googleplus.com/" target="_blank"><i class="fa-brands fa-google"></i></a></li>

                <li><a href="http://www.pinterest.com/" target="_blank" ><i class="fa-brands fa-pinterest-p"></i></a></li>

            </ul>
        </div>


        <!-- INTRODUCCION --> 

    <marquee> <h1 style="color: red; font-family: Arial;"></h1></marquee>

    <br>

    <section class="contenedor centrado">

        <h2>¿Qué ofrecemos? </h2>
        <br>

        <div class="iconos-nosotros">

            <div class="iconos">
                <img src="Imagenes/pastelessencillos.jpg" alt="">
                <h3>Pasteles sencillos</h3>
                <p>Contamos con una gran variedad de riquísimos pasteles. De Zanahoria,
                    Mantequilla, Tres Leches, Tronco de Chocolate, Trufa de Chocolate y muchos más.
                    Nuestros pasteles de Tres Leches y de Mantequilla pueden ser preparados 
                    con nuestros decorados y cubiertas.</p>
            </div>


            <div class="iconos">
                <img src="Imagenes/decorado3.jpg" alt="">
                <h3>Decorados especiales</h3>
                <p>Nuestros pasteles de Tres Leches y de Mantequilla 
                    pueden ser decorados con cualquiera de nuestras distintas coberturas. 
                    También hacemos coberturas personalizadas con la imagen que tu quieras, 
                    logos de compañias, escudos de escuelas, personajes infantiles y de caricatura 
                    y muchos más.</p>
            </div>

            <div class="iconos">
                <img src="Imagenes/postresTemporada.jpg" alt="">
                <h3>Postres de temporada</h3>
                <p>Nunca te quedaras con antojo con la gran variedad de postres que tenemos.
                    Galletas ó Pastitas, Flan regular y Napolitano, Gelatinas, Pay Regular y Helado, 
                    Rollo Helado de Chocolate y muchos más.</p>
            </div>

        </div>

    </section>

    <!-- FIN INTRODUCCION -->

    <!-- DESARROLLO -->

    <br><br>

    <section class="contenedor centrado">

        <h2>Variedad</h2>
        <br>

        <div class="iconos-nosotros">

            <div class="iconos">
                <a><img src="Imagenes/PostresChocolat.jpg" alt=""></a>
                <h3>Postres de Chocolate</h3>
                <p>
                    Contamos con todo tipo de recetas deliciosas: tartas y pasteles, bizcochos de chocolate, galletas, mousses, cookies, natillas de chocolate... ¿Y qué decir de la sublime combinación de sabores de las recetas elaboradas con tres chocolates? Con tantas opciones entre las que escoger ¡imposible no caer en la tentación!                   </p>

            </div>


            <div class="iconos">
                <a><img src="Imagenes/Pays.jpg" alt=""></a>
                <h3>Tartas</h3>

                <p>
                    Ahora que ya el invierno va quedando atrás nos esperan temperaturas más agradables con días más largos en los que disfrutar de la naturaleza en todo su esplendor. . Las fresas y fresones son ideales para lucirse con postres de todo tipo, y tenemos muchas recetas de tartas de fresas, frutillas y  diferentes ingredientes perfectas para cualquier ocasión.
                </p>
            </div>

            <div class="iconos">
                <a><img src="Imagenes/Kekes.jpg" alt=""></a>
                <h3>Kekes a su gusto</h3>

                <p>
                    Y es que las recetas de queques se utilizan como base para preparar muchísimos otros postres, pero también para prepararlas y comerlas simplemente como desayuno, merienda o postres después de una comida acompañadas de tu bebida preferida.    
                </p>

            </div>

        </div>

    </section>

    <br><br>


    <section class="contenedor centrado">

        <h2>Destacados</h2>
        <br>

        <div class="iconos-nosotros">

            <div class="iconos">
                <a><img src="Imagenes/Destacados/Tarta_de_chocolate.jpg" alt="" height="350"></a>
                <h3>Tarta de Chocolate</h3>
                <p>
                    Nuestro presentable y bien recibida torta de chocolate, cubierta de una superficie de vainilla y presentada con hojas de menta, es nuestro aperitivo más popular en nuestra tienda. Usando productos naturales e ingredientes de calidad, se pudo popularizar este exquisito postre de crepuscular.</p>

            </div>


            <div class="iconos">
                <a><img src="Imagenes/Destacados/Tres_Leches.jpg" alt="" height="350"></a>
                <h3>Pastel Tres Leches</h3>

                <p>
                    La esponjosidad del postre 3 leches es irresistible para los amantes del dulce. Como su nombre lo indica, se trata de una exquisitez que se elabora con tres tipos de leche: leche líquida, leche condensada y crema de leche. Es por si uno de los aperitivos mas pedidos y populares entre la clientela.
                </p>
            </div>

            <div class="iconos">
                <a><img src="Imagenes/Destacados/Bayas.jpg" alt="" height="350" width="580"></a>
                <h3>Tarta de Bayas</h3>

                <p>
                    Nuestra tarta de bayas es un postre hecho con bayas sazonadas horneadas en una masa de hojaldre. Se usan diferentes tipos de bayas para realizar el postre, y hay una amplia gama de estilos de tarta de bayas hechas en todo el mundo, desde tarta de fresa y ruibarbo hasta tarta de arándano dulce, siendo el mas popular entre niños.
                </p>

            </div>

        </div>

        <br><br>


        <div class="iconos-nosotros">

            <div class="iconos">
                <a><img src="Imagenes/Destacados/Blueberries.jpg" alt="" height="380"></a>
                <h3>Pastel de Arándano con fresas</h3>
                <p>
                    La tarta de arándanos es una tarta con relleno de arándanos, con un toque de frutillas es un postre especialmente para fortalecer el paladar dulce de la clientela, siendo uno de los mas exquisitos y sabrosos pasteles del establecimiento.
                </p>

            </div>


            <div class="iconos">
                <a><img src="Imagenes/Destacados/Selva_negra.jpg" alt="" height="380"></a>
                <h3>Pastel Selva Negra</h3>

                <p>
                    Uno de los mas populares pasteles en nuestro amado Perú, amado por muchos y delicioso para otros, siendo un postre de talla internacional y nacional, ah estado popularizado en todo el Perú, por ello, lo tenemos en el podio de nuestro mas exquisitos postres.
                </p>
            </div>

            <div class="iconos">
                <a><img src="Imagenes/Destacados/Flan.jpg" alt="" height="380"></a>
                <h3>Flan con Moras</h3>

                <p>
                    Uno de los postres unicos y delicioso, nuestro Flan acompañado de moras con un toque de miel por dentro, es uno de los postres mas populares entre los niños y adolecentes. Teniendo una textura muy blanda y suave para el paladar, es una delicia para nuestros clientes.
                </p>

            </div>



        </div>

    </section>

    <br><br> 


    <section class="contenedor centrado">

        <h2>Conoce a nuestros chefs</h2>
        <br>

        <div class="iconos-nosotros">




            <div class="iconos">
                <a><img src="Imagenes/chef2.jpg" alt=""></a>
                <h3>Lucas Casanova</h3>
                <p> Se define como postrero, es un adicto confeso a los helados y también fan de todo aquello que tenga un punto divertido o raro. En sus platos no faltan referencias artísticas y culturales, siendo el viaje una de sus mayores fuentes de inspiración. Tampoco se olvida de sus raíces y constantemente recurre a recuerdos de infancia a la hora de elaborar sus postres. Define a la pasteleria como divertida, fresca, sencilla, con una gran exigencia de calidad y que busca hacer sonreír a todos los públicos. </p>
            </div>

            <div class="iconos">
                <a><img src="Imagenes/chef1.jpg" alt=""></a>
                <h3>Diana Acevedo</h3>
                <p>
                    Mi nombre es Diana Acevedo, soy pastelera y cocinera. Mi proceso con la gastronomía empieza desde que soy muy pequeña. En mi casa mi mamá tenía una panadería, ese trabajo lo alternaba con la docencia. Recuerdo que en esa época ella no tenía muchos trabajadores en el negocio, nosotros le ayudábamos, pero debo confesar que a mí el servicio al cliente no me llamaba mucho la atención. A mí me gustaba era la cocina, estar adentro aprendiendo, mirando, experimentando. Me hice amiga de los panaderos y pasteleros. Les pedía los recortes y pedazos que sobraban de la producción, y ellos me dejaban jugar. Era muy divertido.
                <p>
            </div>

            <div class="iconos">
                <a><img src="Imagenes/chef3.jpg" alt=""></a>
                <h3>Miguel Asturias</h3>
                <p>“Cuando era niño, en vez de comer dulces, comía frutas, es la naturaleza que siempre me inspiró. Algunas frutas son muy buenas si se degustan naturalmente pero aún mejores cuando concentras el sabor. ¡Sólo estoy satisfecho cuando mi postre es mejor que la fruta que lo inspiró!
                    Soy un hombre a quien le gusta la simplicidad y mi trabajo es dictado por las estaciones del año. </p>
            </div>

        </div>

    </section>


    <br><br>
    <br><br>



    <!-- FIN DESARROLLO -->

    <!-- RESEÑAS -->

    <br><br>
    <marquee><h1 style="color: red; font-family: Arial;"> Mejores reseñas</h1></marquee>

    <br><br>
    <br><br>

    <!-- PRIMERA RESEÑA-->

    <figure class="resenias">
        <figcaption>
            <blockquote>
                <p>La perseverancia es digna de admiración, estos postres que he degustado han sido de una calidad sutil, pero a la vez refinada.</p>
            </blockquote>
            <h3>Yajaira Ortega</h3>
            <h4>General Manager of Restaurant Línia - Barcelona</h4>
        </figcaption>
    </figure>

    <!-- SEGUNDA RESEÑA -->

    <figure class="resenias">
        <figcaption>
            <blockquote>
                <p>Tiene una distribución de sabores muy bien lograda, digna de una pastelería de primera categoría.</p>
            </blockquote>
            <h3>Eduardo Mondragón</h3>
            <h4>Chef Patissier</h4>
        </figcaption>
    </figure>

    <!-- TERCERA RESEÑA -->

    <figure class="resenias">
        <figcaption>
            <blockquote>
                <p>De las mejores pastelerías que hay en la ciudad, sin duda mi favorita.</p>
            </blockquote>
            <h3>Marco Soto</h3>
            <h4>Client</h4>
        </figcaption>
    </figure>


    <br><br>
    <br><br>
    <br><br><br>

    <!-- FIN RESEÑA -->

    <?php
    include 'piedepagina.php';
    ?>

</body>

</html>
